const state={themes:window.THEME_COLLECTION||[],query:"",category:"all"};const grid=document.querySelector("#themes"),count=document.querySelector("#count"),search=document.querySelector("#search"),select=document.querySelector("#category"),chips=document.querySelector("#category-chips"),dialog=document.querySelector("#details"),details=document.querySelector("#details-content"),stats=document.querySelector("#hero-stats");
const esc=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
function filtered(){const q=state.query.trim().toLowerCase();return state.themes.filter(t=>(state.category==="all"||t.category===state.category)&&(!q||[t.name,t.category,t.description,t.repo,t.status].join(" ").toLowerCase().includes(q)))}
function card(t){const live=t.demoUrl?`<a class="button button--primary" href="${t.demoUrl}">Live demo</a>`:`<span class="button disabled">Demo unavailable</span>`;return `<article class="card"><div class="card__preview"><img loading="lazy" src="${t.preview}" alt="${esc(t.name)} preview artwork"></div><div class="card__body"><div class="card__top"><div><div class="card__category">${esc(t.category)}</div><h3>${esc(t.name)}</h3></div><span class="card__status">${esc(t.status)}</span></div><p class="card__desc">${esc(t.description)}</p><div class="meta-row"><span class="meta-pill">${esc(t.category)}</span><span class="meta-pill">${t.demoUrl?"Demo available":"Manual review"}</span></div><div class="actions">${live}<a class="button" href="${t.repoUrl}">Repository</a><button class="button" data-details="${esc(t.repo)}">Details</button></div></div></article>`}
function sync(){chips.querySelectorAll("[data-category]").forEach(b=>b.classList.toggle("active",b.dataset.category===state.category));select.value=state.category}
function render(){const items=filtered();count.textContent=`${items.length} of ${state.themes.length} themes`;grid.innerHTML=items.length?items.map(card).join(""):`<div class="empty">No themes match that search right now.</div>`;sync()}
function controls(){const cats=[...new Set(state.themes.map(t=>t.category))].sort();select.innerHTML=`<option value="all">All categories</option>`+cats.map(c=>`<option value="${c}">${c}</option>`).join("");chips.innerHTML=`<button class="chip-button active" data-category="all">All themes</button>`+cats.map(c=>`<button class="chip-button" data-category="${c}">${c}</button>`).join("")}
function hero(){const cats=new Set(state.themes.map(t=>t.category)),available=state.themes.filter(t=>t.demoUrl).length,unavailable=state.themes.length-available;stats.innerHTML=`<div class="stat-card"><span class="stat-card__value">${state.themes.length}</span><span class="stat-card__label">Theme entries</span></div><div class="stat-card"><span class="stat-card__value">${available}</span><span class="stat-card__label">Available now</span></div><div class="stat-card"><span class="stat-card__value">${cats.size}</span><span class="stat-card__label">Style groups</span></div><div class="stat-card"><span class="stat-card__value">${unavailable}</span><span class="stat-card__label">Manual review</span></div>`}
function openDetails(repo){const t=state.themes.find(x=>x.repo===repo);if(!t)return;const live=t.demoUrl?`<a class="button button--primary" href="${t.demoUrl}">Open live demo</a>`:`<span class="button disabled">Live demo unavailable</span>`;details.innerHTML=`<img class="dialog-preview" src="${t.preview}" alt="${esc(t.name)} preview artwork"><p class="eyebrow">${esc(t.category)}</p><h2>${esc(t.name)}</h2><p>${esc(t.description)}</p><p><span class="status-badge">${esc(t.status)}</span></p><div class="dialog-links">${live}<a class="button" href="${t.repoUrl}">Open repository</a><a class="button" href="${t.issuesUrl}">Report issue or request addition</a></div>`;dialog.showModal()}
hero();controls();render();search.addEventListener("input",e=>{state.query=e.target.value;render()});select.addEventListener("change",e=>{state.category=e.target.value;render()});chips.addEventListener("click",e=>{const b=e.target.closest("[data-category]");if(!b)return;state.category=b.dataset.category;render()});grid.addEventListener("click",e=>{const b=e.target.closest("[data-details]");if(b)openDetails(b.dataset.details)});document.querySelector("#close").onclick=()=>dialog.close();dialog.addEventListener("click",e=>{if(e.target===dialog)dialog.close()});