
const S={all:[],q:"",cat:"all"};const shelves=document.querySelector("#shelves"),count=document.querySelector("#result-count"),query=document.querySelector("#query"),category=document.querySelector("#category"),runes=document.querySelector("#category-runes"),dialog=document.querySelector("#detail"),body=document.querySelector("#detail-body");
const esc=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
function list(){const q=S.q.toLowerCase().trim();return S.all.filter(t=>(S.cat==="all"||t.category===S.cat)&&(!q||[t.name,t.description,t.category].join(" ").toLowerCase().includes(q)))}
function tome(t){const demo=t.demoUrl?`<a href="${t.demoUrl}">Open demo</a>`:`<span class="disabled">Unavailable</span>`;return `<article class="tome"><div class="preview"><img loading="lazy" src="${t.preview}" alt="${esc(t.name)} preview"></div><div class="tome-body"><div class="tag">${esc(t.category)}</div><h3>${esc(t.name)}</h3><p>${esc(t.description)}</p><div class="actions">${demo}<a href="${t.repoUrl}">Repository</a><button data-open="${esc(t.repo)}">Inspect</button></div></div></article>`}
function render(){const items=list();count.textContent=`${items.length} spells indexed`;shelves.innerHTML=items.map(tome).join("")||`<p>No themes found in this shelf.</p>`;runes.querySelectorAll("button").forEach(b=>b.classList.toggle("active",b.dataset.cat===S.cat))}
function controls(){const cats=[...new Set(S.all.map(t=>t.category))].sort();category.innerHTML=`<option value="all">All shelves</option>`+cats.map(c=>`<option>${c}</option>`).join("");runes.innerHTML=`<button class="active" data-cat="all">All shelves</button>`+cats.map(c=>`<button data-cat="${c}">${c}</button>`).join("")}
function inspect(repo){const t=S.all.find(x=>x.repo===repo);if(!t)return;body.innerHTML=`<img class="detail-img" src="${t.preview}" alt=""><p class="smallcap">${esc(t.category)}</p><h2>${esc(t.name)}</h2><p>${esc(t.description)}</p><div class="actions">${t.demoUrl?`<a href="${t.demoUrl}">Open demo</a>`:""}<a href="${t.repoUrl}">Repository</a><a href="${t.issuesUrl}">Report issue</a></div>`;dialog.showModal()}
fetch("themes.json").then(r=>r.json()).then(d=>{S.all=d;controls();render()});query.oninput=e=>{S.q=e.target.value;render()};category.onchange=e=>{S.cat=e.target.value;render()};runes.onclick=e=>{const b=e.target.closest("[data-cat]");if(b){S.cat=b.dataset.cat;category.value=S.cat;render()}};shelves.onclick=e=>{const b=e.target.closest("[data-open]");if(b)inspect(b.dataset.open)};document.querySelector("#close").onclick=()=>dialog.close();
