window.THEME_COLLECTION = [
  {
    "repo": "a-master-artificer",
    "name": "A Master Artificer",
    "category": "Developer & Desktop",
    "description": "A workshop-inspired developer portfolio with astrolabe-like details, handcrafted interface elements, and a polished inventor\u2019s-desk atmosphere.",
    "status": "Available",
    "repoUrl": "https://github.com/apursley2012/a-master-artificer",
    "demoUrl": "https://apursley2012.github.io/a-master-artificer/",
    "issuesUrl": "https://github.com/apursley2012/a-master-artificer/issues/new/choose",
    "preview": "assets/previews/a-master-artificer-preview.png"
  },
  {
    "repo": "aurora-borealis",
    "name": "Aurora Borealis",
    "category": "Space & Sci-Fi",
    "description": "A luminous portfolio interface inspired by northern lights, atmospheric gradients, and quiet night-sky exploration.",
    "status": "Available",
    "repoUrl": "https://github.com/apursley2012/aurora-borealis",
    "demoUrl": "https://apursley2012.github.io/aurora-borealis/",
    "issuesUrl": "https://github.com/apursley2012/aurora-borealis/issues/new/choose",
    "preview": "assets/previews/aurora-borealis-preview.png"
  },
  {
    "repo": "aurora-cosmos",
    "name": "Aurora Cosmos",
    "category": "Space & Sci-Fi",
    "description": "A celestial portfolio theme with cosmic depth, glowing accents, and a dreamy observatory-window presentation.",
    "status": "Available",
    "repoUrl": "https://github.com/apursley2012/aurora-cosmos",
    "demoUrl": "https://apursley2012.github.io/aurora-cosmos/",
    "issuesUrl": "https://github.com/apursley2012/aurora-cosmos/issues/new/choose",
    "preview": "assets/previews/aurora-cosmos.svg"
  },
  {
    "repo": "aurora-drift",
    "name": "Aurora Drift",
    "category": "Space & Sci-Fi",
    "description": "A drifting-space portfolio experience with soft aurora color fields, floating visual layers, and a calm futuristic mood.",
    "status": "Available",
    "repoUrl": "https://github.com/apursley2012/aurora-drift",
    "demoUrl": "https://apursley2012.github.io/aurora-drift/",
    "issuesUrl": "https://github.com/apursley2012/aurora-drift/issues/new/choose",
    "preview": "assets/previews/aurora-drift-preview.png"
  },
  {
    "repo": "cmd-core",
    "name": "CMD Core",
    "category": "Developer & Desktop",
    "description": "A command-center portfolio built around terminal energy, system-core styling, and a precise technical presentation.",
    "status": "Available",
    "repoUrl": "https://github.com/apursley2012/cmd-core",
    "demoUrl": "https://apursley2012.github.io/cmd-core/",
    "issuesUrl": "https://github.com/apursley2012/cmd-core/issues/new/choose",
    "preview": "assets/previews/cmd-core.svg"
  },
  {
    "repo": "color-melt",
    "name": "Color Melt",
    "category": "Colorful & Creative",
    "description": "A fluid, color-forward portfolio with layered gradients, energetic transitions, and an art-studio-meets-digital-canvas personality.",
    "status": "Available",
    "repoUrl": "https://github.com/apursley2012/color-melt",
    "demoUrl": "https://apursley2012.github.io/color-melt/",
    "issuesUrl": "https://github.com/apursley2012/color-melt/issues/new/choose",
    "preview": "assets/previews/color-melt-preview.png"
  },
  {
    "repo": "colorful",
    "name": "Colorful",
    "category": "Colorful & Creative",
    "description": "A bright, expressive portfolio theme with cheerful color blocking, playful contrast, and a friendly creative identity.",
    "status": "Available",
    "repoUrl": "https://github.com/apursley2012/colorful",
    "demoUrl": "https://apursley2012.github.io/colorful/",
    "issuesUrl": "https://github.com/apursley2012/colorful/issues/new/choose",
    "preview": "assets/previews/colorful-preview.png"
  },
  {
    "repo": "cosmic-developer",
    "name": "Cosmic Developer",
    "category": "Space & Sci-Fi",
    "description": "A developer portfolio framed as a voyage through code, projects, and skills with a sleek cosmic interface.",
    "status": "Available",
    "repoUrl": "https://github.com/apursley2012/cosmic-developer",
    "demoUrl": "https://apursley2012.github.io/cosmic-developer/",
    "issuesUrl": "https://github.com/apursley2012/cosmic-developer/issues/new/choose",
    "preview": "assets/previews/cosmic-developer-preview.png"
  },
  {
    "repo": "dark-retro-web",
    "name": "Dark Retro Web",
    "category": "Retro & Arcade",
    "description": "A shadowy retro-web portfolio with early-internet attitude, moody contrast, and nostalgic digital texture.",
    "status": "Available",
    "repoUrl": "https://github.com/apursley2012/dark-retro-web",
    "demoUrl": "https://apursley2012.github.io/dark-retro-web/",
    "issuesUrl": "https://github.com/apursley2012/dark-retro-web/issues/new/choose",
    "preview": "assets/previews/dark-retro-web.svg"
  },
  {
    "repo": "dev-nexus",
    "name": "Dev Nexus",
    "category": "Space & Sci-Fi",
    "description": "A technical hub-style portfolio that organizes projects, skills, and experience through a sleek connected-system interface.",
    "status": "Available",
    "repoUrl": "https://github.com/apursley2012/dev-nexus",
    "demoUrl": "https://apursley2012.github.io/dev-nexus/",
    "issuesUrl": "https://github.com/apursley2012/dev-nexus/issues/new/choose",
    "preview": "assets/previews/dev-nexus.svg"
  },
  {
    "repo": "dev.void",
    "name": "Dev.Void",
    "category": "Space & Sci-Fi",
    "description": "A dark-space developer portfolio with minimal void-like visuals, crisp technical details, and a quietly futuristic atmosphere.",
    "status": "Available",
    "repoUrl": "https://github.com/apursley2012/dev.void",
    "demoUrl": "https://apursley2012.github.io/dev.void/",
    "issuesUrl": "https://github.com/apursley2012/dev.void/issues/new/choose",
    "preview": "assets/previews/dev.void-preview.png"
  },
  {
    "repo": "dev_mode",
    "name": "Dev_Mode",
    "category": "Developer & Desktop",
    "description": "A clean developer-mode portfolio with code-inspired presentation, focused navigation, and a practical technical personality.",
    "status": "Available",
    "repoUrl": "https://github.com/apursley2012/dev_mode",
    "demoUrl": "https://apursley2012.github.io/dev_mode/",
    "issuesUrl": "https://github.com/apursley2012/dev_mode/issues/new/choose",
    "preview": "assets/previews/dev_mode-preview.png"
  },
  {
    "repo": "dev_mode-arcade",
    "name": "Dev_Mode Arcade",
    "category": "Retro & Arcade",
    "description": "A developer portfolio styled like an arcade cabinet in debug mode, mixing technical content with playful game-screen energy.",
    "status": "Available",
    "repoUrl": "https://github.com/apursley2012/dev_mode-arcade",
    "demoUrl": "https://apursley2012.github.io/dev_mode-arcade/",
    "issuesUrl": "https://github.com/apursley2012/dev_mode-arcade/issues/new/choose",
    "preview": "assets/previews/dev_mode-arcade-preview.png"
  },
  {
    "repo": "developer-dossier",
    "name": "Developer Dossier",
    "category": "Developer & Desktop",
    "description": "A dossier-style portfolio that presents work history, projects, and skills like a classified professional file.",
    "status": "Available",
    "repoUrl": "https://github.com/apursley2012/developer-dossier",
    "demoUrl": "https://apursley2012.github.io/developer-dossier/",
    "issuesUrl": "https://github.com/apursley2012/developer-dossier/issues/new/choose",
    "preview": "assets/previews/developer-dossier-preview.png"
  },
  {
    "repo": "devhaunt",
    "name": "DevHaunt",
    "category": "Mystical & Haunted",
    "description": "A haunted developer portfolio where technical work meets eerie interface details, shadowy panels, and playful supernatural atmosphere.",
    "status": "Available",
    "repoUrl": "https://github.com/apursley2012/devhaunt",
    "demoUrl": "https://apursley2012.github.io/devhaunt/",
    "issuesUrl": "https://github.com/apursley2012/devhaunt/issues/new/choose",
    "preview": "assets/previews/devhaunt-preview.png"
  },
  {
    "repo": "digital-alchemy",
    "name": "Digital Alchemy",
    "category": "Mystical & Haunted",
    "description": "A mystical developer portfolio that blends arcane symbols, coded experiments, and a refined digital-alchemist aesthetic.",
    "status": "Available",
    "repoUrl": "https://github.com/apursley2012/digital-alchemy",
    "demoUrl": "https://apursley2012.github.io/digital-alchemy/",
    "issuesUrl": "https://github.com/apursley2012/digital-alchemy/issues/new/choose",
    "preview": "assets/previews/digital-alchemy-preview.png"
  },
  {
    "repo": "digital-coven",
    "name": "Digital Coven",
    "category": "Mystical & Haunted",
    "description": "A witchy digital portfolio with coven-inspired styling, dark interface panels, and a collaborative spellbook-of-projects feeling.",
    "status": "Available",
    "repoUrl": "https://github.com/apursley2012/digital-coven",
    "demoUrl": "https://apursley2012.github.io/digital-coven/",
    "issuesUrl": "https://github.com/apursley2012/digital-coven/issues/new/choose",
    "preview": "assets/previews/digital-coven.svg"
  },
  {
    "repo": "doom",
    "name": "Doom",
    "category": "Retro & Arcade",
    "description": "A heavy, game-inspired portfolio with ominous interface styling, bold contrast, and an unapologetically intense presentation.",
    "status": "Available",
    "repoUrl": "https://github.com/apursley2012/doom",
    "demoUrl": "https://apursley2012.github.io/doom/",
    "issuesUrl": "https://github.com/apursley2012/doom/issues/new/choose",
    "preview": "assets/previews/doom-preview.png"
  },
  {
    "repo": "dyed-in-the-wool",
    "name": "Dyed in the Wool",
    "category": "Colorful & Creative",
    "description": "A textile-inspired creative portfolio with rich color, handcrafted warmth, and a cozy but polished studio identity.",
    "status": "Available",
    "repoUrl": "https://github.com/apursley2012/dyed-in-the-wool",
    "demoUrl": "https://apursley2012.github.io/dyed-in-the-wool/",
    "issuesUrl": "https://github.com/apursley2012/dyed-in-the-wool/issues/new/choose",
    "preview": "assets/previews/dyed-in-the-wool-preview.png"
  },
  {
    "repo": "fortune-seeker",
    "name": "Fortune Seeker",
    "category": "Mystical & Haunted",
    "description": "A divination-inspired portfolio that feels like searching through cards, clues, and glowing paths toward the next project.",
    "status": "Available",
    "repoUrl": "https://github.com/apursley2012/fortune-seeker",
    "demoUrl": "https://apursley2012.github.io/fortune-seeker/",
    "issuesUrl": "https://github.com/apursley2012/fortune-seeker/issues/new/choose",
    "preview": "assets/previews/fortune-seeker-preview.png"
  },
  {
    "repo": "full-moon",
    "name": "Full Moon",
    "category": "Mystical & Haunted",
    "description": "A moonlit portfolio with nocturnal colors, mystical details, and a calm supernatural glow.",
    "status": "Available",
    "repoUrl": "https://github.com/apursley2012/full-moon",
    "demoUrl": "https://apursley2012.github.io/full-moon/",
    "issuesUrl": "https://github.com/apursley2012/full-moon/issues/new/choose",
    "preview": "assets/previews/full-moon-preview.png"
  },
  {
    "repo": "full-stack-sorcery",
    "name": "Full-Stack Sorcery",
    "category": "Mystical & Haunted",
    "description": "A magical developer portfolio that frames full-stack skills, projects, and experience as a carefully organized grimoire.",
    "status": "Available",
    "repoUrl": "https://github.com/apursley2012/full-stack-sorcery",
    "demoUrl": "https://apursley2012.github.io/full-stack-sorcery/",
    "issuesUrl": "https://github.com/apursley2012/full-stack-sorcery/issues/new/choose",
    "preview": "assets/previews/full-stack-sorcery-preview.png"
  },
  {
    "repo": "geocities.exe",
    "name": "GeoCities.exe",
    "category": "Retro & Arcade",
    "description": "A chaotic-fun retro-web portfolio with GeoCities-era spirit, executable-file attitude, and delightfully nostalgic presentation.",
    "status": "Available",
    "repoUrl": "https://github.com/apursley2012/geocities.exe",
    "demoUrl": "https://apursley2012.github.io/geocities.exe/",
    "issuesUrl": "https://github.com/apursley2012/geocities.exe/issues/new/choose",
    "preview": "assets/previews/geocities.exe-preview.png"
  },
  {
    "repo": "good-vibes",
    "name": "Good Vibes",
    "category": "Colorful & Creative",
    "description": "A cheerful personal portfolio with sunny energy, approachable styling, and an upbeat creative presence.",
    "status": "Available",
    "repoUrl": "https://github.com/apursley2012/good-vibes",
    "demoUrl": "https://apursley2012.github.io/good-vibes/",
    "issuesUrl": "https://github.com/apursley2012/good-vibes/issues/new/choose",
    "preview": "assets/previews/good-vibes-preview.png"
  },
  {
    "repo": "magical",
    "name": "Magical",
    "category": "Mystical & Haunted",
    "description": "A soft magical portfolio with whimsical accents, glowing details, and a welcoming enchanted atmosphere.",
    "status": "Available",
    "repoUrl": "https://github.com/apursley2012/magical",
    "demoUrl": "https://apursley2012.github.io/magical/",
    "issuesUrl": "https://github.com/apursley2012/magical/issues/new/choose",
    "preview": "assets/previews/magical.svg"
  },
  {
    "repo": "mission-control",
    "name": "Mission Control",
    "category": "Space & Sci-Fi",
    "description": "A mission-control portfolio with dashboard-style panels, technical readouts, and a focused aerospace-command mood.",
    "status": "Available",
    "repoUrl": "https://github.com/apursley2012/mission-control",
    "demoUrl": "https://apursley2012.github.io/mission-control/",
    "issuesUrl": "https://github.com/apursley2012/mission-control/issues/new/choose",
    "preview": "assets/previews/mission-control-preview.png"
  },
  {
    "repo": "my-webring",
    "name": "My Webring",
    "category": "Retro & Arcade",
    "description": "A personal web-ring portfolio with handcrafted internet nostalgia, community-page charm, and old-web personality.",
    "status": "Available",
    "repoUrl": "https://github.com/apursley2012/my-webring",
    "demoUrl": "https://apursley2012.github.io/my-webring/",
    "issuesUrl": "https://github.com/apursley2012/my-webring/issues/new/choose",
    "preview": "assets/previews/my-webring-preview.png"
  },
  {
    "repo": "mystery-haunting",
    "name": "Mystery Haunting",
    "category": "Mystical & Haunted",
    "description": "A story-like haunted portfolio with mysterious navigation, atmospheric visual details, and a playful paranormal edge.",
    "status": "Available",
    "repoUrl": "https://github.com/apursley2012/mystery-haunting",
    "demoUrl": "https://apursley2012.github.io/mystery-haunting/",
    "issuesUrl": "https://github.com/apursley2012/mystery-haunting/issues/new/choose",
    "preview": "assets/previews/mystery-haunting-preview.png"
  },
  {
    "repo": "neon-retro-arcade",
    "name": "Neon Retro Arcade",
    "category": "Retro & Arcade",
    "description": "A neon arcade portfolio with glowing controls, energetic retro color, and a high-score-screen sense of fun.",
    "status": "Available",
    "repoUrl": "https://github.com/apursley2012/neon-retro-arcade",
    "demoUrl": "https://apursley2012.github.io/neon-retro-arcade/",
    "issuesUrl": "https://github.com/apursley2012/neon-retro-arcade/issues/new/choose",
    "preview": "assets/previews/neon-retro-arcade.svg"
  },
  {
    "repo": "neon-retro-sys_admin",
    "name": "Neon Retro Sys_Admin",
    "category": "Retro & Arcade",
    "description": "A neon systems-administrator portfolio with retro terminal styling, infrastructure flavor, and a bright technical interface.",
    "status": "Available",
    "repoUrl": "https://github.com/apursley2012/neon-retro-sys_admin",
    "demoUrl": "https://apursley2012.github.io/neon-retro-sys_admin/",
    "issuesUrl": "https://github.com/apursley2012/neon-retro-sys_admin/issues/new/choose",
    "preview": "assets/previews/neon-retro-sys_admin-preview.png"
  },
  {
    "repo": "neon-retro-web",
    "name": "Neon Retro Web",
    "category": "Retro & Arcade",
    "description": "A glowing retro-web portfolio with cyber-neon accents, nostalgic browser energy, and a lively digital-night aesthetic.",
    "status": "Available",
    "repoUrl": "https://github.com/apursley2012/neon-retro-web",
    "demoUrl": "https://apursley2012.github.io/neon-retro-web/",
    "issuesUrl": "https://github.com/apursley2012/neon-retro-web/issues/new/choose",
    "preview": "assets/previews/neon-retro-web.svg"
  },
  {
    "repo": "nightshade",
    "name": "Nightshade",
    "category": "Mystical & Haunted",
    "description": "A dark botanical portfolio with poisonous-flower elegance, moody contrast, and an enchanted nocturnal atmosphere.",
    "status": "Available",
    "repoUrl": "https://github.com/apursley2012/nightshade",
    "demoUrl": "https://apursley2012.github.io/nightshade/",
    "issuesUrl": "https://github.com/apursley2012/nightshade/issues/new/choose",
    "preview": "assets/previews/nightshade-preview.png"
  },
  {
    "repo": "observatory",
    "name": "Observatory",
    "category": "Space & Sci-Fi",
    "description": "An observatory-inspired portfolio with celestial navigation, scientific curiosity, and a quiet stargazing interface.",
    "status": "Available",
    "repoUrl": "https://github.com/apursley2012/observatory",
    "demoUrl": "https://apursley2012.github.io/observatory/",
    "issuesUrl": "https://github.com/apursley2012/observatory/issues/new/choose",
    "preview": "assets/previews/observatory-preview.png"
  },
  {
    "repo": "oracle",
    "name": "Oracle",
    "category": "Mystical & Haunted",
    "description": "A divination-interface portfolio with arcane symbols, dramatic contrast, and an immersive digital-oracle presentation.",
    "status": "Available",
    "repoUrl": "https://github.com/apursley2012/oracle",
    "demoUrl": "https://apursley2012.github.io/oracle/",
    "issuesUrl": "https://github.com/apursley2012/oracle/issues/new/choose",
    "preview": "assets/previews/oracle-preview.png"
  },
  {
    "repo": "orbital-station",
    "name": "Orbital Station",
    "category": "Space & Sci-Fi",
    "description": "A space-station portfolio with modular panels, orbital-system styling, and a clean futuristic operations feel.",
    "status": "Available",
    "repoUrl": "https://github.com/apursley2012/orbital-station",
    "demoUrl": "https://apursley2012.github.io/orbital-station/",
    "issuesUrl": "https://github.com/apursley2012/orbital-station/issues/new/choose",
    "preview": "assets/previews/orbital-station.svg"
  },
  {
    "repo": "player-one",
    "name": "Player One",
    "category": "Retro & Arcade",
    "description": "A player-select portfolio with game-screen personality, achievement-style presentation, and playful interactive energy.",
    "status": "Available",
    "repoUrl": "https://github.com/apursley2012/player-one",
    "demoUrl": "https://apursley2012.github.io/player-one/",
    "issuesUrl": "https://github.com/apursley2012/player-one/issues/new/choose",
    "preview": "assets/previews/player-one.svg"
  },
  {
    "repo": "press-start",
    "name": "Press Start",
    "category": "Retro & Arcade",
    "description": "A retro game-inspired portfolio that invites visitors into projects and experience with a classic press-start welcome.",
    "status": "Available",
    "repoUrl": "https://github.com/apursley2012/press-start",
    "demoUrl": "https://apursley2012.github.io/press-start/",
    "issuesUrl": "https://github.com/apursley2012/press-start/issues/new/choose",
    "preview": "assets/previews/press-start-preview.png"
  },
  {
    "repo": "retro-arcade",
    "name": "Retro Arcade",
    "category": "Retro & Arcade",
    "description": "A vintage arcade portfolio with pixel-era inspiration, bold game-room colors, and an energetic nostalgic interface.",
    "status": "Available",
    "repoUrl": "https://github.com/apursley2012/retro-arcade",
    "demoUrl": "https://apursley2012.github.io/retro-arcade/",
    "issuesUrl": "https://github.com/apursley2012/retro-arcade/issues/new/choose",
    "preview": "assets/previews/retro-arcade.svg"
  },
  {
    "repo": "retro-dev",
    "name": "Retro Dev",
    "category": "Retro & Arcade",
    "description": "A developer portfolio with retro-computing charm, practical project organization, and an old-school technical personality.",
    "status": "Available",
    "repoUrl": "https://github.com/apursley2012/retro-dev",
    "demoUrl": "https://apursley2012.github.io/retro-dev/",
    "issuesUrl": "https://github.com/apursley2012/retro-dev/issues/new/choose",
    "preview": "assets/previews/retro-dev.svg"
  },
  {
    "repo": "retro-windows",
    "name": "Retro Windows",
    "category": "Retro & Arcade",
    "description": "A desktop-style portfolio inspired by classic Windows interfaces, familiar panels, and nostalgic productivity software.",
    "status": "Available",
    "repoUrl": "https://github.com/apursley2012/retro-windows",
    "demoUrl": "https://apursley2012.github.io/retro-windows/",
    "issuesUrl": "https://github.com/apursley2012/retro-windows/issues/new/choose",
    "preview": "assets/previews/retro-windows-preview.png"
  },
  {
    "repo": "space-mission",
    "name": "Space Mission",
    "category": "Space & Sci-Fi",
    "description": "A mission-log portfolio that presents projects, skills, and experience as milestones in an ongoing space expedition.",
    "status": "Available",
    "repoUrl": "https://github.com/apursley2012/space-mission",
    "demoUrl": "https://apursley2012.github.io/space-mission/",
    "issuesUrl": "https://github.com/apursley2012/space-mission/issues/new/choose",
    "preview": "assets/previews/space-mission-preview.png"
  },
  {
    "repo": "spell-index",
    "name": "Spell Index",
    "category": "Mystical & Haunted",
    "description": "A spellbook-index portfolio with neatly cataloged projects, mystical organization, and a practical enchanted-library feel.",
    "status": "Available",
    "repoUrl": "https://github.com/apursley2012/spell-index",
    "demoUrl": "https://apursley2012.github.io/spell-index/",
    "issuesUrl": "https://github.com/apursley2012/spell-index/issues/new/choose",
    "preview": "assets/previews/spell-index-preview.png"
  },
  {
    "repo": "spooky",
    "name": "Spooky",
    "category": "Mystical & Haunted",
    "description": "A Halloween-flavored portfolio with atmospheric shadows, playful scares, and an approachable haunted-house personality.",
    "status": "Available",
    "repoUrl": "https://github.com/apursley2012/spooky",
    "demoUrl": "https://apursley2012.github.io/spooky/",
    "issuesUrl": "https://github.com/apursley2012/spooky/issues/new/choose",
    "preview": "assets/previews/spooky.svg"
  },
  {
    "repo": "spooky-dev",
    "name": "Spooky Dev",
    "category": "Mystical & Haunted",
    "description": "A spooky developer portfolio with eerie decorative details, dark technical panels, and a playful Halloween-coded edge.",
    "status": "Available",
    "repoUrl": "https://github.com/apursley2012/spooky-dev",
    "demoUrl": "https://apursley2012.github.io/spooky-dev/",
    "issuesUrl": "https://github.com/apursley2012/spooky-dev/issues/new/choose",
    "preview": "assets/previews/spooky-dev.svg"
  },
  {
    "repo": "sys.witch",
    "name": "Sys.Witch",
    "category": "Mystical & Haunted",
    "description": "A system-witch portfolio that mixes terminal-like structure with magical details and a sharp technical identity.",
    "status": "Available",
    "repoUrl": "https://github.com/apursley2012/sys.witch",
    "demoUrl": "https://apursley2012.github.io/sys.witch/",
    "issuesUrl": "https://github.com/apursley2012/sys.witch/issues/new/choose",
    "preview": "assets/previews/sys.witch-preview.png"
  },
  {
    "repo": "sys.witch-v2",
    "name": "Sys.Witch V2",
    "category": "Mystical & Haunted",
    "description": "An expanded system-witch portfolio with a richer magical interface, technical structure, and upgraded cyber-occult atmosphere.",
    "status": "Available",
    "repoUrl": "https://github.com/apursley2012/sys.witch-v2",
    "demoUrl": "https://apursley2012.github.io/sys.witch-v2/",
    "issuesUrl": "https://github.com/apursley2012/sys.witch-v2/issues/new/choose",
    "preview": "assets/previews/sys.witch-v2-preview.png"
  },
  {
    "repo": "telemetry",
    "name": "Telemetry",
    "category": "Space & Sci-Fi",
    "description": "A telemetry-dashboard portfolio with signal-inspired details, status-panel organization, and a precise data-driven mood.",
    "status": "Available",
    "repoUrl": "https://github.com/apursley2012/telemetry",
    "demoUrl": "https://apursley2012.github.io/telemetry/",
    "issuesUrl": "https://github.com/apursley2012/telemetry/issues/new/choose",
    "preview": "assets/previews/telemetry.svg"
  },
  {
    "repo": "the-artisan-developer",
    "name": "The Artisan Developer",
    "category": "Developer & Desktop",
    "description": "A craft-focused developer portfolio with workshop warmth, thoughtful detail, and a refined handmade-tech identity.",
    "status": "Available",
    "repoUrl": "https://github.com/apursley2012/the-artisan-developer",
    "demoUrl": "https://apursley2012.github.io/the-artisan-developer/",
    "issuesUrl": "https://github.com/apursley2012/the-artisan-developer/issues/new/choose",
    "preview": "assets/previews/the-artisan-developer-preview.png"
  },
  {
    "repo": "the-craft",
    "name": "The Craft",
    "category": "Mystical & Haunted",
    "description": "A mystical craft-inspired portfolio with coven-like atmosphere, dramatic styling, and expressive supernatural personality.",
    "status": "Available",
    "repoUrl": "https://github.com/apursley2012/the-craft",
    "demoUrl": "https://apursley2012.github.io/the-craft/",
    "issuesUrl": "https://github.com/apursley2012/the-craft/issues/new/choose",
    "preview": "assets/previews/the-craft-preview.png"
  },
  {
    "repo": "top-secret",
    "name": "Top Secret",
    "category": "Manual Review",
    "description": "A classified-file-inspired theme entry reserved for restoration. Its website files are not included in the current archive, so the live demo is intentionally disabled.",
    "status": "Unavailable: website files missing",
    "repoUrl": "https://github.com/apursley2012/top-secret",
    "demoUrl": "",
    "issuesUrl": "https://github.com/apursley2012/top-secret/issues/new/choose",
    "preview": "assets/previews/top-secret-preview.png"
  },
  {
    "repo": "web-surfer",
    "name": "Web Surfer",
    "category": "Developer & Desktop",
    "description": "A breezy web-surfer portfolio with internet-adventure energy, playful navigation, and a colorful digital-wave aesthetic.",
    "status": "Available",
    "repoUrl": "https://github.com/apursley2012/web-surfer",
    "demoUrl": "https://apursley2012.github.io/web-surfer/",
    "issuesUrl": "https://github.com/apursley2012/web-surfer/issues/new/choose",
    "preview": "assets/previews/web-surfer.svg"
  },
  {
    "repo": "web-weaver",
    "name": "Web Weaver",
    "category": "Developer & Desktop",
    "description": "A handcrafted web portfolio inspired by weaving, interconnected projects, and a creative builder\u2019s studio.",
    "status": "Available",
    "repoUrl": "https://github.com/apursley2012/web-weaver",
    "demoUrl": "https://apursley2012.github.io/web-weaver/",
    "issuesUrl": "https://github.com/apursley2012/web-weaver/issues/new/choose",
    "preview": "assets/previews/web-weaver-preview.png"
  },
  {
    "repo": "webmaster",
    "name": "Webmaster",
    "category": "Developer & Desktop",
    "description": "A classic webmaster portfolio with old-web authority, practical navigation, and a nostalgic site-owner control-room feel.",
    "status": "Available",
    "repoUrl": "https://github.com/apursley2012/webmaster",
    "demoUrl": "https://apursley2012.github.io/webmaster/",
    "issuesUrl": "https://github.com/apursley2012/webmaster/issues/new/choose",
    "preview": "assets/previews/webmaster-preview.png"
  },
  {
    "repo": "windows-98-clippy",
    "name": "Windows 98 Clippy",
    "category": "Retro & Arcade",
    "description": "A playful Windows 98-style portfolio featuring Clippy-era charm, desktop nostalgia, and a familiar software-assistant personality.",
    "status": "Available",
    "repoUrl": "https://github.com/apursley2012/windows-98-clippy",
    "demoUrl": "https://apursley2012.github.io/windows-98-clippy/",
    "issuesUrl": "https://github.com/apursley2012/windows-98-clippy/issues/new/choose",
    "preview": "assets/previews/windows-98-clippy.svg"
  },
  {
    "repo": "windows-98-inspired",
    "name": "Windows 98 Inspired",
    "category": "Retro & Arcade",
    "description": "A Windows 98-inspired portfolio with classic desktop framing, nostalgic interface controls, and retro productivity-software charm.",
    "status": "Available",
    "repoUrl": "https://github.com/apursley2012/windows-98-inspired",
    "demoUrl": "https://apursley2012.github.io/windows-98-inspired/",
    "issuesUrl": "https://github.com/apursley2012/windows-98-inspired/issues/new/choose",
    "preview": "assets/previews/windows-98-inspired-preview.png"
  },
  {
    "repo": "windows-old",
    "name": "Windows Old",
    "category": "Retro & Arcade",
    "description": "An old-Windows portfolio with vintage desktop styling, familiar application windows, and a charmingly nostalgic interface.",
    "status": "Available",
    "repoUrl": "https://github.com/apursley2012/windows-old",
    "demoUrl": "https://apursley2012.github.io/windows-old/",
    "issuesUrl": "https://github.com/apursley2012/windows-old/issues/new/choose",
    "preview": "assets/previews/windows-old-preview.jpg"
  },
  {
    "repo": "windows-xp",
    "name": "Windows Xp",
    "category": "Retro & Arcade",
    "description": "A Windows XP-inspired portfolio with bright desktop nostalgia, familiar window styling, and an approachable early-2000s feel.",
    "status": "Available",
    "repoUrl": "https://github.com/apursley2012/windows-xp",
    "demoUrl": "https://apursley2012.github.io/windows-xp/",
    "issuesUrl": "https://github.com/apursley2012/windows-xp/issues/new/choose",
    "preview": "assets/previews/windows-xp-preview.png"
  },
  {
    "repo": "witch.dev",
    "name": "Witch.dev",
    "category": "Mystical & Haunted",
    "description": "A witch-developer portfolio that balances magical details with a concise technical interface and a strong personal brand.",
    "status": "Available",
    "repoUrl": "https://github.com/apursley2012/witch.dev",
    "demoUrl": "https://apursley2012.github.io/witch.dev/",
    "issuesUrl": "https://github.com/apursley2012/witch.dev/issues/new/choose",
    "preview": "assets/previews/witch.dev.svg"
  },
  {
    "repo": "y2k-web",
    "name": "Y2K Web",
    "category": "Retro & Arcade",
    "description": "A Y2K web portfolio with glossy nostalgia, early-2000s internet personality, and playful digital-era styling.",
    "status": "Available",
    "repoUrl": "https://github.com/apursley2012/y2k-web",
    "demoUrl": "https://apursley2012.github.io/y2k-web/",
    "issuesUrl": "https://github.com/apursley2012/y2k-web/issues/new/choose",
    "preview": "assets/previews/y2k-web-preview.png"
  }
];
