
const S={data:[],q:"",cat:"all"};const grid=document.querySelector("#grid"),rail=document.querySelector("#featured"),search=document.querySelector("#search"),cat=document.querySelector("#category"),count=document.querySelector("#count"),modal=document.querySelector("#modal"),body=document.querySelector("#body");
const esc=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
function list(){const q=S.q.toLowerCase().trim();return S.data.filter(t=>(S.cat==="all"||t.category===S.cat)&&(!q||[t.name,t.description,t.category].join(" ").toLowerCase().includes(q)))}
function card(t){return `<article class="case"><img loading="lazy" src="${t.preview}" alt=""><p class="meta">${esc(t.category)}</p><h3>${esc(t.name)}</h3><p>${esc(t.description)}</p><div class="links">${t.demoUrl?`<a href="${t.demoUrl}">DEMO</a>`:""}<a href="${t.repoUrl}">SOURCE</a><button data-open="${esc(t.repo)}">DETAILS</button></div></article>`}
function feature(t){return `<article class="feature"><img src="${t.preview}" alt=""><small>${esc(t.category)}</small><h3>${esc(t.name)}</h3><div class="links">${t.demoUrl?`<a href="${t.demoUrl}">OPEN</a>`:""}<button data-open="${esc(t.repo)}">DETAILS</button></div></article>`}
function render(){const items=list();count.textContent=`${items.length} RECORDS ACTIVE`;grid.innerHTML=items.map(card).join("");rail.innerHTML=items.slice(0,6).map(feature).join("")}
function open(repo){const t=S.data.find(x=>x.repo===repo);if(!t)return;body.innerHTML=`<img class="detail-img" src="${t.preview}" alt=""><p class="overline">${esc(t.category)}</p><h2>${esc(t.name)}</h2><p>${esc(t.description)}</p><div class="links">${t.demoUrl?`<a href="${t.demoUrl}">OPEN DEMO</a>`:""}<a href="${t.repoUrl}">SOURCE</a><a href="${t.issuesUrl}">REQUEST UPDATE</a></div>`;modal.showModal()}
fetch("themes.json").then(r=>r.json()).then(d=>{S.data=d;cat.innerHTML=`<option value="all">ALL CATEGORIES</option>`+[...new Set(d.map(x=>x.category))].sort().map(c=>`<option>${c}</option>`).join("");render()});search.oninput=e=>{S.q=e.target.value;render()};cat.onchange=e=>{S.cat=e.target.value;render()};document.body.onclick=e=>{const b=e.target.closest("[data-open]");if(b)open(b.dataset.open)};document.querySelector("#close").onclick=()=>modal.close();
